/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.trabajos.vistas;

import com.toedter.calendar.JDateChooser;
import gui.interfaces.IControladorModificarProfesor;
import java.awt.Dialog;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JTextField;


public class VentanaModificarProfesor extends JDialog {
    private IControladorModificarProfesor controlador;
    
    /**
     * Constructor 
     * @param controlador controlador de la ventana
     * @param ventanaPadre ventana padre (VentanaAMTrabajo en este caso)
     */
    public VentanaModificarProfesor(IControladorModificarProfesor controlador, Dialog ventanaPadre) {
        super(ventanaPadre, true);
        this.controlador = controlador;
        initComponents();
    }

    public JDateChooser verFechaDesde() {
        return fechaDesde;
    }
    
    public JDateChooser verFechaHasta() {
        return fechaHasta;
    }

    public JTextField verTxtRazon() {
        return txtRazon;
    }

    public JComboBox<String> verComboProfesores() {
        return comboProfesores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinFieldBeanInfo1 = new com.toedter.components.JSpinFieldBeanInfo();
        jSpinFieldBeanInfo2 = new com.toedter.components.JSpinFieldBeanInfo();
        jTextField5 = new javax.swing.JTextField();
        jSpinField1 = new com.toedter.components.JSpinField();
        txtRazon = new javax.swing.JTextField();
        etqFechaHasta = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fechaHasta = new com.toedter.calendar.JDateChooser();
        etqRazon = new javax.swing.JLabel();
        comboProfesores = new javax.swing.JComboBox<>();
        etqNuevoProfesor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fechaDesde = new com.toedter.calendar.JDateChooser();

        jTextField5.setText("jTextField5");
        jTextField5.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Profesor");

        txtRazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonPresionarTecla(evt);
            }
        });

        etqFechaHasta.setText("Hasta:");

        btnAceptar.setMnemonic('A');
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Modificar Profesor");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarClic(evt);
            }
        });

        btnCancelar.setMnemonic('A');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClic(evt);
            }
        });

        fechaHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaHastaPresionarTecla(evt);
            }
        });

        etqRazon.setText("Razón:");

        comboProfesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        etqNuevoProfesor.setText("Nuevo Profesor:");

        jLabel1.setText("Desde:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqFechaHasta)
                    .addComponent(etqRazon)
                    .addComponent(jLabel1)
                    .addComponent(etqNuevoProfesor))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProfesores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRazon)
                    .addComponent(fechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(fechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqFechaHasta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqRazon)
                    .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqNuevoProfesor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarClic
        controlador.btnAceptarClic(evt);
    }//GEN-LAST:event_btnAceptarClic

    private void btnCancelarClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClic
        controlador.btnCancelarClic(evt);
    }//GEN-LAST:event_btnCancelarClic

    private void txtRazonPresionarTecla(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonPresionarTecla
        this.controlador.txtRazonPresionarTecla(evt);
    }//GEN-LAST:event_txtRazonPresionarTecla

    private void fechaHastaPresionarTecla(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaHastaPresionarTecla
        this.controlador.fechaHastaPresionarTecla(evt);
    }//GEN-LAST:event_fechaHastaPresionarTecla
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboProfesores;
    private javax.swing.JLabel etqFechaHasta;
    private javax.swing.JLabel etqNuevoProfesor;
    private javax.swing.JLabel etqRazon;
    private com.toedter.calendar.JDateChooser fechaDesde;
    private com.toedter.calendar.JDateChooser fechaHasta;
    private javax.swing.JLabel jLabel1;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinFieldBeanInfo jSpinFieldBeanInfo1;
    private com.toedter.components.JSpinFieldBeanInfo jSpinFieldBeanInfo2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtRazon;
    // End of variables declaration//GEN-END:variables
}
